#!/bin/bash
printf "%s \t %s\n" "$(find "$1" -maxdepth 1  -type f | wc -l)" "$1"
find $1 -maxdepth $2 -mindepth 1 -type d | while read dir; do
  printf "%s \t %s\n" "$(find "$dir" -maxdepth 1  -type f | wc -l)" "$dir"
done
